# webserv varsayılan config'i — subject'in IV.3'te istediği tüm directive'leri
# canlı gösterecek şekilde kuruldu (error_page, return, autoindex, upload_path,
# cgi_extension, client_max_body_size, methods, root, index).
server {
    listen 127.0.0.1:8080;
    server_name localhost;
    client_max_body_size 1000000;

    error_page 404 ./www/404.html;
    error_page 500 ./www/500.html;
	error_page 403 ./www/403.html;

    location / {
        root ./www;
        index index.html;
        methods GET;
        autoindex on;
    }

    # HTTP redirect örneği: /eski -> /
    location /eski {
        return /;
    }

    # Dosya upload örneği: POST ile buraya gönderilen her şey ./www/uploads'a yazılır
  location /upload {
    root ./www;
    upload_path ./www/uploads;
    methods POST DELETE;
}

    # CGI örneği: uzantısı .py olan her istek python3 ile çalıştırılır
    location /cgi-bin {
        root ./www/cgi-bin;
        cgi_extension .py;
        methods GET POST;
    }
}

# TODO: GET isteğinde dosyanın izinleri yoksa 403 hatası vermeli, bunu işlemem gerekiyor.
# TODO: upload'da POST ile var olan bir dosyaya tekrar yazınca hala 201 dönüyor, buna bakmam lazım.

