# Ayni bucket (0.0.0.0:8080) icinde IKI server ayni server_name'e (tolga1) sahip.
# Host: tolga1 geldiginde hangisi cevap verecek? Belirsiz -> reddedilmeli.
server {
    listen 0.0.0.0:8080;
    server_name tolga1;
    root ./www;
}
server {
    listen 0.0.0.0:8080;
    server_name tolga2;
    root ./www2;
}
server {
    listen 0.0.0.0:8080;
    server_name tolga1;
    root ./www3;
}
